name: score-models
channels:
  - conda-forge
  - bioconda
dependencies:
  # Core stack
  - python=3.9
  - build
  - bump2version=1.0.1
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - mamba
  - pip
  - twine
  # Standard PyData stack
  - matplotlib
  - numpy
  - pandas
  - scipy
  - cudatoolkit=11.6
  - seaborn
  - cloudpickle
  - scikit-learn
  # Utilities
  - pyprojroot
  - python-dotenv
  - seqlike=1.1.7
  - mafft
  - umap-learn
  # CLI development
  - typer
  - typer-cli
  # Software testing
  - hypothesis
  - pytest
  - pytest-cov
  # Code Style Tools
  - black
  - darglint
  - flake8
  - interrogate
  - pre-commit
  - pylint
  # Documentation
  - tqdm
  - ffmpeg
  - jupyter-cache
  # pip dependencies
  - pip:
      # Place packages that cannot be installed by conda in this section.
      - mknotebooks
      # To install GPU versions, execute the following command after updating the environment.
      # pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
      - jax==0.4.8
      - jaxlib
      - optax
      - equinox
      - dm-haiku
      - celluloid
      - diffrax
      - chex>=0.1.3
      - shutup==0.2.0
      - wget==3.2 # for downloading FASTA files programmatically.
