name: score-models
channels:
  - conda-forge
dependencies:
  # Core stack
  - python=3.9
  - build
  - bump2version=1.0.1
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - mamba
  - pip
  - twine
  # Standard PyData stack
  - matplotlib
  - numpy
  - pandas
  - scipy
  - cudatoolkit
  - seaborn
  # Utilities
  - pyprojroot
  - python-dotenv
  # CLI development
  - typer
  - typer-cli
  # Software testing
  - hypothesis
  - pytest
  - pytest-cov
  # Code Style Tools
  - black
  - darglint
  - flake8
  - interrogate
  - pre-commit
  - pylint
  # Documentation
  - tqdm
  - ffmpeg
  # pip dependencies
  - pip:
      # Place packages that cannot be installed by conda in this section.
      - mknotebooks
      # To install GPU versions, execute the following command after updating the environment.
      # pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
      - jax
      - jaxlib
      - jaxopt
      - git+git+https://github.com/patrick-kidger/equinox.git@0c21766e46a097581e1c8652895b75bdc78cfdde
      - dm-haiku
      - celluloid
      - elegy
      # Pin minimum chex version once it is released.
      - git+https://github.com/deepmind/chex.git # https://github.com/deepmind/optax/issues/335
