name: score-models
channels:
  - conda-forge
dependencies:
  # Core stack
  - python=3.9
  - build
  - bump2version=1.0.1
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - mamba
  - pip
  - twine
  # Standard PyData stack
  - matplotlib
  - numpy=1.22.2
  - pandas
  - scipy=1.8.0
  - cudatoolkit=11.6
  - seaborn=0.11.2
  # Utilities
  - pyprojroot
  - python-dotenv
  # CLI development
  - typer=0.4.0
  - typer-cli=0.0.12
  # Software testing
  - hypothesis
  - pytest
  # Code Style Tools
  - black
  - darglint
  - flake8
  - interrogate
  - pre-commit
  - pylint
  # Documentation
  - mkdocs
  - mkdocs-material
  - mkdocstrings
  - tqdm
  - ffmpeg
  # pip dependencies
  - pip:
      # Place packages that cannot be installed by conda in this section.
      - mknotebooks
      # To install GPU versions, execute the following command after updating the environment.
      # pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
      - jax==0.3.0
      - jaxlib
      - jaxopt
      - dm-haiku
      - celluloid
