# Run code style checks on each pull request.
name: Code style checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
